### ISSUE TITLE
CentOS-* kitchen tests fail w/ sudo issue

### ISSUE THREAD

**Issue by rjhornsby** [johnbellone/vault-cookbook#78]
There's an issue with converging the cookbook on CentOS (6.x, 7.x) that is related to sudo:

```
...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Sudo failed: Sudo requires a password, please configure it.] on default-centos-72
```

While there's probably a better approach, at least one successful way around this issue seems to be to modify[1] the .kitchen.yml by adding this to each of the centos boxes:

```
    attributes:
      authorization:
        sudo:
          users: ['kitchen']
          passwordless: true
          include_sudoers_d: true
```

This issue is coming up in bento/\* base boxes, as well as puppetlabs-centos-66-64-nocm (nocm == no pre-installed config management tools). If it matters, running Kitchen version 1.13.2 from the chefdk 0.18.30-1.

[1] http://stackoverflow.com/questions/39523883/kitchen-test-failed-sudo-requires-a-password-please-configure-it-on-default-ce
